// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// tpm_func
NumericMatrix tpm_func(double alpha, NumericVector omegas, NumericMatrix resources, NumericVector d, int nc);
RcppExport SEXP steppingstone_tpm_func(SEXP alphaSEXP, SEXP omegasSEXP, SEXP resourcesSEXP, SEXP dSEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omegas(omegasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type resources(resourcesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    rcpp_result_gen = Rcpp::wrap(tpm_func(alpha, omegas, resources, d, nc));
    return rcpp_result_gen;
END_RCPP
}
// walk_func
List walk_func(NumericMatrix tpm, int n, NumericVector xy0, int nc);
RcppExport SEXP steppingstone_walk_func(SEXP tpmSEXP, SEXP nSEXP, SEXP xy0SEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tpm(tpmSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xy0(xy0SEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    rcpp_result_gen = Rcpp::wrap(walk_func(tpm, n, xy0, nc));
    return rcpp_result_gen;
END_RCPP
}
// walk_func_boundary_stop
List walk_func_boundary_stop(NumericMatrix tpm, int n, NumericVector xy0, int nc);
RcppExport SEXP steppingstone_walk_func_boundary_stop(SEXP tpmSEXP, SEXP nSEXP, SEXP xy0SEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tpm(tpmSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xy0(xy0SEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    rcpp_result_gen = Rcpp::wrap(walk_func_boundary_stop(tpm, n, xy0, nc));
    return rcpp_result_gen;
END_RCPP
}
// walk_func_boundary_reflective
List walk_func_boundary_reflective(NumericMatrix tpm, int n, NumericVector xy0, int nc, int max_try);
RcppExport SEXP steppingstone_walk_func_boundary_reflective(SEXP tpmSEXP, SEXP nSEXP, SEXP xy0SEXP, SEXP ncSEXP, SEXP max_trySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tpm(tpmSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xy0(xy0SEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< int >::type max_try(max_trySEXP);
    rcpp_result_gen = Rcpp::wrap(walk_func_boundary_reflective(tpm, n, xy0, nc, max_try));
    return rcpp_result_gen;
END_RCPP
}
// ud_func
List ud_func(NumericMatrix tpm, int n, NumericVector xy0, int nc, int burnin);
RcppExport SEXP steppingstone_ud_func(SEXP tpmSEXP, SEXP nSEXP, SEXP xy0SEXP, SEXP ncSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tpm(tpmSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xy0(xy0SEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(ud_func(tpm, n, xy0, nc, burnin));
    return rcpp_result_gen;
END_RCPP
}
