# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tpm_func <- function(alpha, omegas, resources, d, nc) {
    .Call('steppingstone_tpm_func', PACKAGE = 'steppingstone', alpha, omegas, resources, d, nc)
}

walk <- function(tpm, n, xy0, nc, dp, init_dir = -1L, boundary = 1L, max_try = 100L) {
    .Call('steppingstone_walk', PACKAGE = 'steppingstone', tpm, n, xy0, nc, dp, init_dir, boundary, max_try)
}

ud_func <- function(tpm, n, xy0, nc, burnin, dp, boundary = 1L, init_dir = -1L, max_try = 100L) {
    .Call('steppingstone_ud_func', PACKAGE = 'steppingstone', tpm, n, xy0, nc, burnin, dp, boundary, init_dir, max_try)
}

