# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

foo <- function(x) {
    .Call('steppingstone_foo', PACKAGE = 'steppingstone', x)
}

foo1 <- function(x) {
    .Call('steppingstone_foo1', PACKAGE = 'steppingstone', x)
}

tpm_func <- function(alpha, omegas, resources, d, nc) {
    .Call('steppingstone_tpm_func', PACKAGE = 'steppingstone', alpha, omegas, resources, d, nc)
}

walk_func <- function(tpm, n, xy0, nc) {
    .Call('steppingstone_walk_func', PACKAGE = 'steppingstone', tpm, n, xy0, nc)
}

walk_func_boundary_stop <- function(tpm, n, xy0, nc) {
    .Call('steppingstone_walk_func_boundary_stop', PACKAGE = 'steppingstone', tpm, n, xy0, nc)
}

walk_func_boundary_reflective <- function(tpm, n, xy0, nc, max_try) {
    .Call('steppingstone_walk_func_boundary_reflective', PACKAGE = 'steppingstone', tpm, n, xy0, nc, max_try)
}

ud_func <- function(tpm, n, xy0, nc, burnin) {
    .Call('steppingstone_ud_func', PACKAGE = 'steppingstone', tpm, n, xy0, nc, burnin)
}

walk_func_dp <- function(tpm, n, xy0, nc) {
    .Call('steppingstone_walk_func_dp', PACKAGE = 'steppingstone', tpm, n, xy0, nc)
}

